# Generated by Django 5.2.4 on 2025-08-07 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_experience_professionalprofile_education_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalprofile',
            name='profile_picture',
        ),
    ]
