# Generated by Django 5.2.4 on 2025-08-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_professional_profile_picturee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professionaldocument',
            old_name='file_size',
            new_name='document_size',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='portfolio_document',
        ),
        migrations.RemoveField(
            model_name='portfolioimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='professionaldocument',
            name='document_file',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture_content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='featured_image_content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='featured_image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='featured_image_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='featured_image_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_document_content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_document_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_document_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_document_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolioimage',
            name='image_content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='portfolioimage',
            name='image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolioimage',
            name='image_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolioimage',
            name='image_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professionaldocument',
            name='document_content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='professionaldocument',
            name='document_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professionaldocument',
            name='document_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
