# Generated by Django 5.2.4 on 2025-08-07 18:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_consultationbooking_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consultation_date', models.DateField()),
                ('consultation_time', models.TimeField()),
                ('duration_minutes', models.IntegerField(choices=[(30, '30 minutes'), (60, '1 hour'), (90, '1.5 hours'), (120, '2 hours')], default=60)),
                ('consultation_type', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], default='ONLINE', max_length=10)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('meeting_id', models.CharField(blank=True, max_length=100, null=True)),
                ('meeting_passcode', models.CharField(blank=True, max_length=50, null=True)),
                ('office_address', models.TextField(blank=True, null=True)),
                ('problem_description', models.TextField(help_text='Describe your legal issue or what you need help with')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No Show')], default='PENDING', max_length=15)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded'), ('FAILED', 'Failed')], default='PENDING', max_length=15)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('client_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_bookings', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_bookings', to=settings.AUTH_USER_MODEL)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_bookings', to='core.professionalprofile')),
            ],
            options={
                'db_table': 'consultation_bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('review_text', models.TextField()),
                ('would_recommend', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='core.consultationbooking')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to='core.professionalprofile')),
            ],
            options={
                'db_table': 'consultation_reviews',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalPricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fee_30_min', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('fee_60_min', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('fee_90_min', models.DecimalField(decimal_places=2, default=1400.0, max_digits=10)),
                ('fee_120_min', models.DecimalField(decimal_places=2, default=1800.0, max_digits=10)),
                ('offline_consultation_extra', models.DecimalField(decimal_places=2, default=200.0, max_digits=10)),
                ('accepts_online', models.BooleanField(default=True)),
                ('accepts_offline', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='core.professionalprofile')),
            ],
            options={
                'db_table': 'professional_pricing',
            },
        ),
        migrations.AddIndex(
            model_name='consultationbooking',
            index=models.Index(fields=['consultation_date', 'consultation_time'], name='consultatio_consult_76e75b_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationbooking',
            index=models.Index(fields=['status'], name='consultatio_status_a7c75a_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationbooking',
            index=models.Index(fields=['client'], name='consultatio_client__83dd07_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationbooking',
            index=models.Index(fields=['professional'], name='consultatio_profess_86b3e8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='consultationreview',
            unique_together={('booking', 'client')},
        ),
    ]
