# Generated by Django 5.2.4 on 2025-08-07 18:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_consultationbooking_consultationreview_and_more'),
    ]

    operations = [
        # Remove booking-related models
        migrations.DeleteModel(
            name='ConsultationBooking',
        ),
        migrations.DeleteModel(
            name='ConsultationReview',
        ),
        
        # Create ConsultationSlot model
        migrations.CreateModel(
            name='ConsultationSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('BLOCKED', 'Blocked'), ('HELD', 'Temporarily Held')], default='AVAILABLE', max_length=20)),
                ('held_until', models.DateTimeField(blank=True, null=True)),
                ('custom_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('held_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_slots', to=settings.AUTH_USER_MODEL)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_slots', to='core.professionalprofile')),
            ],
            options={
                'db_table': 'consultation_slots',
                'ordering': ['start_time'],
                'unique_together': {('professional', 'start_time', 'end_time')},
            },
        ),
    ]
