# Generated by Django 5.2.4 on 2025-08-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20250807_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalprofile',
            name='years_of_experience',
            field=models.CharField(blank=True, help_text="e.g., '1-3', '5-10', '10+', etc.", max_length=20, null=True),
        ),
    ]
