# Generated by Django 5.2.4 on 2025-08-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_professionalprofile_years_of_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='videokyc',
            name='session_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videokyc',
            name='video_content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='videokyc',
            name='video_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videokyc',
            name='video_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='videokyc',
            name='video_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
