# Generated by Django 5.2.4 on 2025-08-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_consultationbooking_professionalreviewsummary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationslot',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='consultationslot',
            name='consultation_type',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], default='ONLINE', max_length=10),
        ),
    ]
